on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

name: Test with Code Coverage

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          cd ldtk_map 
          cargo check
          cargo test --all          

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

